### ISSUE TITLE
Meeting #5: Wed Aug 8, 2018. 6-8pm. Location: Chicago Blockchain Center. Topic: ZeppelinOS

### ISSUE THREAD

**Issue by pcowgill** [decentralized-software/chicago#16]
[Google Calendar event](https://calendar.google.com/event?action=TEMPLATE&tmeid=NjR0MDhza2RocXRocHYzYnUybmY3dHZydmtfMjAxODA4MDFUMjMwMDAwWiBnYzMxdHFlMGdua2JzZmc4ajliZWk1ZWRuNEBn&tmsrc=gc31tqe0gnkbsfg8j9bei5edn4%40group.calendar.google.com)

Proposed topic: ZeppelinOS

"ZeppelinOS is an open-source, distributed platform of tools and services on top of the EVM to develop and manage smart contract applications securely."

"ZeppelinOS is an operating system designed specifically for smart contracts. It provides an on-chain set of upgradeable standard libraries, and an incentive structure to continually upgrade and patch itself."

**Comment by mattparlmer** [comment]
@pcowgill Depending on the number of RSVPs we could probably block out a room for a few hours at 1871.

**Comment by pcowgill** [comment]
Yeah, that's a good idea.

I'll work on finding a date for the next one that doesn't conflict with other good meetups soon. Are Wednesdays still best for people?

**Comment by pcowgill** [comment]
Let's plan on Wednesday, August 8th at 6pm!

[Google Calendar event](https://calendar.google.com/event?action=TEMPLATE&tmeid=NjR0MDhza2RocXRocHYzYnUybmY3dHZydmtfMjAxODA4MDFUMjMwMDAwWiBnYzMxdHFlMGdua2JzZmc4ajliZWk1ZWRuNEBn&tmsrc=gc31tqe0gnkbsfg8j9bei5edn4%40group.calendar.google.com)

**Comment by pcowgill** [comment]
Proposed topic: ZeppelinOS
[zeppelinos.org](https://zeppelinos.org/)
[GitHub](https://github.com/zeppelinos)

"ZeppelinOS is an open-source, distributed platform of tools and services on top of the EVM to develop and manage smart contract applications securely."

"ZeppelinOS is an operating system designed specifically for smart contracts. It provides an on-chain set of upgradeable standard libraries, and an incentive structure to continually upgrade and patch itself."

**Comment by pcowgill** [comment]
@mattparlmer Could you please take the lead on booking a room in 1871? I think if we plan for 15 people that should be good.

**Comment by spalladino** [comment]
Hey folks, Santiago from the ZeppelinOS dev team here. Just wanted to tell you that I love the initiative (it's awesome for us to see dev teams working on the tech we're building), and I'd be happy to join for a quick video call if you're interested. The meetup time for me is 8pm-10pm (I'm in GMT-3), so the earlier I can join, the better. Let me know if there's anything in particular you'd like to talk about, or just general discussions on the project! Cheers!

**Comment by pcowgill** [comment]
@spalladino Thanks so much! I'll reach out soon with more details, but for now let's plan on having you video call in on Wed Aug 8 at 6:15pm our time / 8:15pm GMT-3!

**Comment by pcowgill** [comment]
We have a location confirmed for the event!

Chicago Blockchain Center
20 W Kinzie St.
12th floor
Chicago, IL 60654

Please try to arrive at or before 6pm, because @spalladino from Zeppelin will be joining right at 6:15pm central.

If you have any problems finding us, you can reach me at @pcowgill on Telegram or @paulcowgill on Twitter.

**Comment by pcowgill** [comment]
Slight update on the location!

10th floor of 20 W Kinzie St. rather than the 12th floor.

If you have any problems finding us, you can reach me at @pcowgill on Telegram or @paulcowgill on Twitter.
