### ISSUE TITLE
Meeting #6: Wed Sep 5, 2018. 6-8pm. Location: Chicago Blockchain Center. Topic: Generalized state channels

### ISSUE THREAD

**Issue by pcowgill** [decentralized-software/chicago#22]
[Google Calendar event](https://calendar.google.com/event?action=TEMPLATE&tmeid=NjR0MDhza2RocXRocHYzYnUybmY3dHZydmtfMjAxODA5MDVUMjMwMDAwWiBnYzMxdHFlMGdua2JzZmc4ajliZWk1ZWRuNEBn&tmsrc=gc31tqe0gnkbsfg8j9bei5edn4%40group.calendar.google.com&scp=ALL)

**Comment by pcowgill** [comment]
Any requests for the topic for our next meeting on Wed Sep 5?

For the last two we did Drizzle from Truffle Suite and ZeppelinOS.

To throw a few options out there, maybe:
1. [EthQL, GraphQL interface for Ethereum](https://github.com/ConsenSys/ethql)
1. [State channels](https://counterfactual.com/)
1. [Keep, Privacy for Ethereum](https://keep.network/)?

**Comment by pcowgill** [comment]
I just finalized a location for our Wed Sep 5 meeting.

The meeting will be in room 13E (on the 13th floor) in the same building as Chicago Blockchain Center.

20 W Kinzie St
Chicago, IL 60610

**Comment by RickCarlino** [comment]
@pcowgill I can't make it out this week, but in the future, I would be interested in talking about Secure Scuttlebutt. Are topics usually centered around blockchain technology?

Also, Fox.Build Makerspace has an 8,000 square foot building that is free for use. It's a bit of a hike from the city (Geneva metra is the closest train station), but I thought I'd offer just in case there is interest in a suburban venue.

**Comment by pcowgill** [comment]
@RickCarlino Thanks for reaching out! I'll move those topics out to different GitHub issues and respond there.

**Comment by pcowgill** [comment]
Ok, we've got a final topic for the meeting: **Generalized state channels**

The format for this meeting will be a discussion, so I'd recommend doing a little reading beforehand if possible. (But if you can't find some, don't let that stop you from coming!)

Here's some relevant info:
https://medium.com/l4-media/generalized-state-channels-on-ethereum-de0357f5fb44
https://counterfactual.com/
https://l4.ventures/papers/statechannels.pdf
https://github.com/counterfactual
https://medium.com/l4-media/making-sense-of-ethereums-layer-2-scaling-solutions-state-channels-plasma-and-truebit-22cb40dcc2f4

Datetime:
Wed Sep 5 at 6pm (we'll start by 6:10pm at the latest, so aim to arrive on time if you can)

Location:
Room 13E (on the 13th floor) in the same building as Chicago Blockchain Center. 20 W Kinzie St, Chicago, IL 60610

**Comment by Galileo31** [comment]
Paul,
 thanks for arranging this meeting and for putting all of this information together.  I unfortunately have a commitment for an event I RSVP'd for that evening and cannot make it.  I do plan to read all of this material and attend the next event.
  
 Thank you, hope all is going well with you.
  
 Sincerely,
 Brad
  
      _________________________________________________
 Bradley Arlen
 CEO OneMe PBC.
  

----------------------------------------

**Comment by pcowgill** [comment]
Goods news! It looks like we'll have a few remote technical people who know a lot about state channels video-calling in for the discussion!

Here are the projects we'll have people calling in from:
[Counterfactual](https://counterfactual.com/)
[Connext](https://connext.network/)
[Magmo](https://magmo.com/)

**Comment by pcowgill** [comment]
Hope to see you all this evening!

**Comment by pcowgill** [comment]
Oh, and `ConsenSys` will be covering food and drinks tonight! Thanks to Donnie Benjamin for that!
