### ISSUE TITLE
Non-Chicago locations

### ISSUE THREAD

**Issue by pcowgill** [decentralized-software/chicago#23]
Over in a different GitHub issue, @RickCarlino said, "...Fox.Build Makerspace has an 8,000 square foot building that is free for use. It's a bit of a hike from the city (Geneva metra is the closest train station), but I thought I'd offer just in case there is interest in a suburban venue."

Thanks for offering! I think this Chicago repo should focus only on the city of Chicago to make sure there's a critical mass of people at the meetings, but if lots of folks would prefer to meet in the suburbs, you're more than welcome to create a new repo under the https://github.com/decentralized-software org called `chicago-suburbs` or `chicago-suburbs-west` (If you'd like to do that and you encounter any issues, let me know - I may not have the permissions configured correctly.)

While we're on the topic of non-Chicago locations, I'll also point out that we're open to people making a repo for other cities anywhere in the world.

**Comment by RickCarlino** [comment]
Thanks, @pcowgill , I've made the group. I will add the README when I get home from work today. Thanks for the quick reply!

**Comment by pcowgill** [comment]
@RickCarlino Great! You can feel free to customize things as you see fit, but also feel free to use our `README` almost verbatim.

The only part I'll ask that you definitely keep in order to stick with the ethos of this group is our code of conduct emphasizing inclusion.

**Comment by pcowgill** [comment]
I think I'm going to convert this issue to a section in the README https://github.com/decentralized-software/chicago

**Comment by pcowgill** [comment]
https://github.com/decentralized-software/chicago/pull/24
