### ISSUE TITLE
Meeting #7: Wed Oct 3, 2018. 6-8pm. Location: 20 W Kinzie St. Topic: IPFS and Filecoin

### ISSUE THREAD

**Issue by pcowgill** [decentralized-software/chicago#25]
Meeting 7
Wed Oct 3, 2018. 6-8pm.
Location: 20 W Kinzie St.
Topic: IPFS and Filecoin

[Add to Google Calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=NjR0MDhza2RocXRocHYzYnUybmY3dHZydmtfMjAxODEwMDNUMjMwMDAwWiBnYzMxdHFlMGdua2JzZmc4ajliZWk1ZWRuNEBn&tmsrc=gc31tqe0gnkbsfg8j9bei5edn4%40group.calendar.google.com)

**Comment by pcowgill** [comment]
One option for a topic for Wed Oct 3 would be this recent update on IPFS and Filecoin progress. https://filecoin.io/blog/update-2018-q1-q2/

Thoughts?

**Comment by thomasj02** [comment]
I would be pretty interested in IPFS/Filecoin

**Comment by pcowgill** [comment]
Since there wasn't a flood of responses saying that people will be gone for SF Blockchain Week other than one person in the group chat on Keybase, I think we should stick with Wed Oct 3 for this one.

**Comment by pcowgill** [comment]
Please plan on reading up a bit before the meeting, since the format for this one is a technical group discussion.

While we've had people from projects call in for past meetups (and some of the upcoming ones), the format for this time is a group discussion. So please plan on reading a bit about IPFS and Filecoin - especially [this link](https://filecoin.io/blog/update-2018-q1-q2/) - ahead of time. Thanks!

**Comment by pcowgill** [comment]
Here's a recent report on the state of IPFS that we also can discuss this week:

https://ipfs.io/ipfs/QmRU1jJ1kNd9fTzjFwM4X9YtA2wfXN1W2eFK7mgTMJ8xgK

(Bonus points since it's hosted using IPFS.)

**Comment by RickCarlino** [comment]
Any info on which room it's in? Just showed up but reception had no room info.

**Comment by pcowgill** [comment]
@RickCarlino I'll come down and let you in. 12D but a keycard is required. On my way.
