### ISSUE TITLE
 Meeting #8: Wed Nov 7, 2018. 6-8pm. Location: Aon Center. Topic: GraphQL-like interfaces for Ethereum

### ISSUE THREAD

**Issue by pcowgill** [decentralized-software/chicago#26]

**Comment by pcowgill** [comment]
FYI I also made a Meetup event for this month's meeting to help with discovery for other folks who may be interested. https://www.meetup.com/Decentralized-Software-Chicago/events/255433634/

But this GitHub issue remains the canonical source of info.

**Comment by pcowgill** [comment]
Looking forward to seeing lots of you this Wednesday at 6pm!

We've got a location - it's 200 E Randolph Suite 200 (the Aon Center / Microsoft building).

**Important:** If you're planning on coming, please email paul@cowgill.io with your first and last name for building security.

Please read up on these two projects ahead of time so you'll have more context for participating in the discussion:

- https://thegraph.com/
- https://github.com/ConsenSys/ethql

At least one of the two projects will have someone from their technical team video-calling in to field our questions, and then for the rest of the time we'll chat about how to get started using and/or contributing to these projects and whatever else we want.

P.S. Thanks to Imran for helping out with the room for this month's meeting.

P.P.S. If you have any issues getting in, I'm `pcowgill` on Telegram.

**Comment by pcowgill** [comment]
Hi all - FYI we need the final list of first and last names for tomorrow's meeting by **3pm today**. It's fine to send your name even if you end up deciding not to attend. You can send them to `paul@cowgill.io`.

**Comment by lostghost** [comment]
Hey Paul, it looks like some of the presenters will be remote. Is there any chance that other participants can call in as well?

**Comment by pcowgill** [comment]
@lostghost Hey, thanks for checking. There's a chance - A/V is always a bit tricky at a new location, though, so it's tough to say. If you message me on Telegram at `pcowgill` around the time of the event, I'll know for sure. I wish I had a simpler answer - thanks!

**Comment by pcowgill** [comment]
(I put all of the names from the Chicago GitHub team for this org on the list just in case, so feel free to decide to come tonight at the last minute. We’ll start promptly at 6pm.)

**Comment by pcowgill** [comment]
See you all today at 6pm! From 6 to 6:30 we can chat and make sure everyone’s on the same page with some background info on the problem this project solves and the technologies they’re using, and then Yaniv from The Graph will be joining remotely at 6:30 to explain the project from their perspective and to field our questions.

Here are the READMEs for The Graph’s main repos in case you want to check them out before tonight:

https://github.com/graphprotocol/graph-node/blob/master/README.md

https://github.com/graphprotocol/graph-cli/blob/master/README.md

https://github.com/graphprotocol/graph-ts/blob/master/README.md

And here’s some info on GraphQL for any of you who haven’t played with it yet: https://graphql.org/
