### ISSUE TITLE
Meeting #9: Mon Dec 17. 6-8pm. Location: WeWork 111 W Illinois St. Topic: Secure Scuttlebutt

### ISSUE THREAD

**Issue by pcowgill** [decentralized-software/chicago#27]
https://www.meetup.com/Decentralized-Software-Chicago/events/256270103/

**Comment by pcowgill** [comment]
Are there any particular teams you all think we should reach out to to potentially video-call in for this meeting (the December one, that is - we're all set for the November one)?

**Comment by pcowgill** [comment]
I think I'm going to move this to Mon Dec 3. That way I can book a room for free through Meetup (for some reason there's only availability on Mondays).

**Comment by pcowgill** [comment]
Never mind, the size of the rooms available that day was too small. I'll delete the last comment and this one.

**Comment by RickCarlino** [comment]
@pcowgill I reached out to some folks on the Scuttleverse to see if there is any interest. Will keep you posted. Also, sorry for the slow reply on this one- did some travel this month.

**Comment by pcowgill** [comment]
How about this project? https://darkcrystal.pw/

**Comment by pcowgill** [comment]
We've got a lead on potentially getting some SSB folks to join. @RickCarlino, thanks for your help with that.

Any major objections to Mon Dec 17 for the next meeting? I just booked a WeWork room from 6-8pm on that date.

**Comment by evbogue** [comment]
@pcowgill hey! @RickCarlino reached out on ssb, and I got flagged down by rabble and punkmunk. @gwenbell and I are 100% up for attending your event. 

Did we meet at a Chicago meetup before, like Chicago Node.js? Your name seems familiar from somewhere...

It'd also be cool to get some other ssbc folks in the room via WebRTC to talk about the projects they are building on ssb.

**Comment by RickCarlino** [comment]
Hi, @evbogue ! I was just about to email you. I have not been to many meetups recently, but your name does sound familiar. Perhaps we have crossed paths before.

Super excited to get this many people in one place talking about SSB. I am going to start investigating the AV options (and fallback options) to make sure everything goes smoothly. I've been told folks have had good luck with `Zoom`, so I am going to check that out.

**Comment by pcowgill** [comment]
@evbogue I wasn't before, but I am now. I'm `@E0OfhF9v02ST2M2+SOY7N0oO49lr11yGIji745JrYoA=.ed25519`.

Yep, that's my understanding of Dark Crystal too.

Those people would be great. I'll follow up with you on ssb to see if you have their contact info.

**Comment by pcowgill** [comment]
See you all tonight!

How to find us: We'll be in room 5D. Please bring a photo id and check in as a guest of Paul Cowgill at the front desk. Message Paul on Telegram (`pcowgill` is his handle) if you have any problems getting in.

**Comment by pcowgill** [comment]
The event will start at 6pm. **Please try to arrive by 6:15pm at the latest.**

The remote SSB projects will be calling in and explaining the tech behind their projects and fielding questions over video call from 6:30pm to 7:30pm.

From 7:30pm to 8pm we'll have an internal discussion about how SSB fits into the broader decentralized software ecosystem. We can also chat about any other questions you may have about SSB. We have a hard stop at 8. Thanks!

https://www.scuttlebutt.nz/

**Comment by evbogue** [comment]
@pcowgill See you tonight. I'm going to private message you on ssb our full legal names for 111 W Illinois security, just in case!

**Comment by pcowgill** [comment]
Here's a tweet to get the word out about tonight in case that's helpful:

https://twitter.com/paulcowgill/status/1074727641712865282
