### ISSUE TITLE
[Related high-quality events] Wed Sep 26, 2018. BOB {Developers} - Blockstack. 6:30-9pm. Location: mHUB 

### ISSUE THREAD

**Issue by pcowgill** [decentralized-software/chicago#29]
[Meetup link](https://www.meetup.com/Bitcoin-Open-Blockchain-Community-Chicago/events/254793018/)

**Comment by GambolingPangolin** [comment]
[Here][pres] is the video from the presentation.

[pres]: https://www.youtube.com/watch?v=uaS1ObtiiBE
