### ISSUE TITLE
Figure out location of first meeting

### ISSUE THREAD

**Issue by pcowgill** [decentralized-software/chicago#3]

**Comment by MercedesMane** [comment]
We can do Catapult Chicago.

**Comment by pcowgill** [comment]
Yeah, Catapult Chicago would be great. This is the address, right?

321 N. Clark Street
Suite 2550, Chicago, IL

**Comment by MercedesMane** [comment]
correct!

**Comment by pcowgill** [comment]
I can't imagine people will have any problems with Catapult for the location, so I'll mark this issue as resolved.

**Comment by pcowgill** [comment]
It turns out in https://github.com/decentralized-software/chicago/issues/6 that we didn't meet the criteria for booking a room in Catapult. @MercedesMane suggested mHub or Connectory as alternatives, and I think either of those would be a great space for this.

Does anyone have any connections at mHub or Connectory to help with booking a room for Wed Mar 7 at 6pm?

**Comment by pcowgill** [comment]
mHub responded to my event space request saying that they would have let us use the space, but that date doesn't work. Fingers crossed for Connectory to pan out.

**Comment by MercedesMane** [comment]
I am waiting to hear back from the Connectory. 

Mercedes Mane

**Comment by pcowgill** [comment]
I've got TechNexus Conference Room A booked for us for Wed Mar 7 at 6pm.

20 North Wacker Drive #1200, Chicago, IL

**Comment by MercedesMane** [comment]
Perfect! Thank you!

Mercedes Mane
