### ISSUE TITLE
Pick a format for the meetings

### ISSUE THREAD

**Issue by pcowgill** [decentralized-software/chicago#4]
Suggestions welcome

**Comment by MercedesMane** [comment]
1) find out people's interest (intro style)
2) Summary of the top tech out there in terms of blockchain and example of their usage cases, who uses them and how
3) list top usage cases (by crypot or token)
4) vote on which one to deep dive and do some hands one work/examples

**Comment by jongear** [comment]
@MercedesMane is right. Discovery might be the best avenue followed by a brief "here is the state of the community".  

I know Ethereum token development is supported on [Azure Blockchain](https://azure.microsoft.com/en-us/solutions/blockchain/).  Which more than likely means AWS and GCP will be releasing support soon as well.
