### ISSUE TITLE
Picking a recurring day for these meetings

### ISSUE THREAD

**Issue by pcowgill** [decentralized-software/chicago#5]
How does 3rd Tuesday of the month sound for these meetings?

The next three would be:

- Tue Feb 20
- Tue Mar 20
- Tue Apr 17

Based on the conversation in [this issue](https://github.com/decentralized-software/chicago/issues/3), I think we'll go with [Catapult Chicago](https://goo.gl/maps/7PJmkpCmpyJ2) for the location.

@redsquirrel @adisney @xiaoyao1991 @KiranPanesar @adamyala @leavenstee @FourSigma @jongear @MercedesMane @ijerrod @beingrishy I won't mention everyone on future issues, but if you'd like to be notified of new issues for this repo going forward, click `Watch` towards the upper right of this window. (Or if you're trying to steer clear of more notifications, that's cool too.)

**Comment by redsquirrel** [comment]
No need to work around me, but Tuesdays won't work for me. Wednesdays are my only option.

**Comment by FourSigma** [comment]
Tuesdays works for me.

**Comment by KiranPanesar** [comment]
Either Tuesdays or Wednesdays will generally work for me.

**Comment by pcowgill** [comment]
Ok, let's plan on Tue Feb 20 for the first one, and we can try for a Wednesday for the second meeting (exact date T.B.D.).

**Comment by MercedesMane** [comment]
Wednesday would be petered for me, soccer night is Tuesday :).

Thanks!

**Comment by pcowgill** [comment]
Wed the 21st is the node meetup, and Wed the 28th is the React meetup, so I'd like to avoid competing with those if possible.

Wed Mar 7 looks good, though.

**Comment by jongear** [comment]
Mar 7th works for me :+1:

**Comment by MercedesMane** [comment]
👍

Mercedes Mane

**Comment by redsquirrel** [comment]
I'll be there 👍

**Comment by pcowgill** [comment]
Great! Wed Mar 7 it is.

**Comment by adisney** [comment]
I'll see you all there!

**Comment by pcowgill** [comment]
Let's tentatively plan on the first Wednesday of each month going forward, if that works for people.

Wed Mar 7
Wed Apr 4
Wed May 2

**Comment by pcowgill** [comment]
First Wednesday of the month seems like a good rhythm.

Whenever that doesn't work, we can do the second Wednesday.

In Apr I can't make it on Wed Apr 4, so let's aim for Wed Apr 11.
