### ISSUE TITLE
Meeting #1: Wed Mar 7, 2018. 6-8pm. TechNexus Conference Room A.

### ISSUE THREAD

**Issue by pcowgill** [decentralized-software/chicago#6]
[Add this event to your Google Calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=NDllMnBsdnVmMTI2NXVybTllcGxhcDAwb2RfMjAxODAyMjFUMDAwMDAwWiBwYXVsZGF2aWRjb3dnaWxsQG0&tmsrc=pauldavidcowgill%40gmail.com)

**Comment by pcowgill** [comment]
@MercedesMane can you help with booking some space in Catapult for this date? Thanks!

How does 6pm sound?

**Comment by MercedesMane** [comment]
Alright, I tried to reserve a room but I was told that reservations are only for alumni (which I am) to have board or investor meeting (which this meeting is not) plus it would be after hr, and that is another problem.

Sorry, we need to find another place. mHub might be another option, or the Connectory, I will check on rules for getting some space at both of those.

Mercedes Mane

**Comment by pcowgill** [comment]
Thanks for trying to book a room at Catapult, oh well. I reopened https://github.com/decentralized-software/chicago/issues/3 so we can work on finding an alternate location.

**Comment by pcowgill** [comment]
Reminder that this will be this Wednesday! Looking forward to it.

Wed Mar 7, 2018
6-8pm

TechNexus Conference Room A
20 N Wacker
Ste 1200
Chicago, IL 60606

**Comment by pcowgill** [comment]
You can use this link to [add the event to your google calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=NDllMnBsdnVmMTI2NXVybTllcGxhcDAwb2RfMjAxODAyMjFUMDAwMDAwWiBwYXVsZGF2aWRjb3dnaWxsQG0&tmsrc=pauldavidcowgill%40gmail.com)

**Comment by redsquirrel** [comment]
Sadly, it looks like I'll have to miss this first meeting. Something came up. Sorry!

**Comment by MercedesMane** [comment]
Everyone,

I will try to make it tonight, but there is a chance I might not. I have been under the weather the last few days and depending how the next few hrs progress I might not be able to leave the house.

Hope see meet everyone soon!

Cheers!

Mercedes Mane

**Comment by adisney** [comment]
I'm afraid I'm going to have a tough time getting to this, as well. I look forward to the next event!

**Comment by pcowgill** [comment]
I don’t think so, but if you have any problems getting in I’m pcowgill on Telegram
