### ISSUE TITLE
Find a sponsor so we can get food

### ISSUE THREAD

**Issue by pcowgill** [decentralized-software/chicago#7]
Otherwise I recommend grabbing food from 5pm to 6pm before the meeting

**Comment by pcowgill** [comment]
@gperez13 has generously offered to help with this - thanks!

**Comment by gperez13** [comment]
You bet @pcowgill!

**Comment by pcowgill** [comment]
The Chicago Blockchain Project has generously offered to cover food and drinks for our next meeting on June 13th (https://github.com/decentralized-software/chicago/issues/11).

Thanks!

If you have any dietary restrictions, please let me know and we’ll aim to accommodate them.

**Comment by pcowgill** [comment]
ConsenSys has generously offered to cover food and drinks for our next meeting tomorrow on Wed Sep 5 (https://github.com/decentralized-software/chicago/issues/22).

If you have any dietary restrictions, please let me know and we’ll aim to accommodate them!
