### ISSUE TITLE
Meeting #2: Wed Apr 11, 2018. 6-8pm. TechNexus conference room B

### ISSUE THREAD

**Issue by pcowgill** [decentralized-software/chicago#8]
Meeting 2: Wed Apr 11, 2018. 6-8pm. Location T.B.D.

The first Wednesday of the month would have be Wed Apr 4, but I can't make that date work, so let's do the second meeting on Wed Apr 11.

**Comment by pcowgill** [comment]
Update: Got a location!

Meeting 2 
Wed Apr 11, 2018
6-8pm
TechNexus conference room B
20 N Wacker
Ste 1200
Chicago, IL 60606

Note that last time we were in conference room A, not B. So it's a different room.

[Add this event to your Google Calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=NjR0MDhza2RocXRocHYzYnUybmY3dHZydmtfMjAxODA0MDRUMjMwMDAwWiBwYXVsZGF2aWRjb3dnaWxsQG0&tmsrc=pauldavidcowgill%40gmail.com)

**Comment by gabivoicu** [comment]
@pcowgill Trying to add the event my Google Calendar and I get a `Could not find the requested event.` message (at the bottom of the screen).

**Comment by pcowgill** [comment]
@gabivoicu Sorry about that. I made a couple changes to the event, but I'm not sure if that will fix it yet. I'll let you know when I've confirmed it's working.

This probably still won't work, but just in case it does:
[Add this event to your Google Calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=NjR0MDhza2RocXRocHYzYnUybmY3dHZydmtfMjAxODA0MDRUMjMwMDAwWiBwYXVsZGF2aWRjb3dnaWxsQG0&tmsrc=pauldavidcowgill%40gmail.com)

**Comment by pcowgill** [comment]
I think the problem was that I added the event to a private calendar. I created a new public calendar and moved the event to that one.

[Hopefully it works this time](https://calendar.google.com/event?action=TEMPLATE&tmeid=NjR0MDhza2RocXRocHYzYnUybmY3dHZydmtfMjAxODA0MDRUMjMwMDAwWiBnYzMxdHFlMGdua2JzZmc4ajliZWk1ZWRuNEBn&tmsrc=gc31tqe0gnkbsfg8j9bei5edn4%40group.calendar.google.com)

**Comment by pcowgill** [comment]
Reminder that this is this Wednesday!

**Comment by pcowgill** [comment]
Feel free to glance at this topics for discussion GitHub issue ahead of tonight's meeting https://github.com/decentralized-software/chicago/issues/9

**Comment by adisney** [comment]
Also, [here is an interesting article](https://www.bloomberg.com/view/articles/2018-04-12/theranos-could-use-some-more-money) I came upon today relevant to some of our ICO discussion yesterday. For those of you that don't know, Matt Levine is a noted bitcoin sceptic (a self proclaimed 'no-coiner') and writes some very well written and well thought out articles for Bloomberg.

I will quote the relevant portion:

> Meanwhile, here is an argument that "the use of SAFTs" -- Simple Agreements for Future Tokens, in which companies do initial coin offerings by private placements of securities that eventually flip into non-security "utility tokens" when their projects go live -- "should be DEAD." The theory is that the SEC considers even "utility tokens" -- tokens that can actually be used to do transactions in a working network, instead of having only speculative value -- to be securities, and so those tokens would need to be registered, and doing an unregistered sale of securities (SAFTs) that can flip into registered securities (tokens) is a no-no. I am not convinced. No one really knows how the SEC would treat a working "utility token," because they basically don't exist. The closest things we have are tokens like Bitcoin and Ether, which can be used in robust networks, and which the SEC has not, so far, tried to regulate as securities. I suspect if someone built a token-based network, and the tokens could really be used to buy and sell some real product on that network, and the tokens' value was relatively stable and tied to the value of the product rather than a speculative bet on the network, then that really wouldn't be a security, and a SAFT that flipped into that sort of token would be fine. I suppose the worry is that the SEC will step in to shut down SAFTs long before we can ever find out.

So if the SEC comes in and shuts down SAFTs (Simple Agreement for Future Tokens) that don't properly register as securities, that'll put a damper on ICOs in general but not invalidate them entirely as fundraising mechanisms.

**Comment by adisney** [comment]
Apologies for the spam, but I forgot to link the article explaining why SAFTs should be dead.

https://www.crowdfundinsider.com/2018/03/131044-initial-coin-offerings-why-the-saft-is-dead/
