### ISSUE TITLE
Topics for discussion

### ISSUE THREAD

**Issue by pcowgill** [decentralized-software/chicago#9]
Here are topics that interest people, based on the Typeform results. I sorted them by category.

**Protocols**
Ethereum / Solidity (9)
Hashgraph (2)
IPFS
Qtum
IOTA
Hyperledger
Lisk
EOS
Dfinity
Blockstack

**Specific languages**
~~Serpent (Smart contract language, alternative to Solidity)~~
Viper (Smart contract language, alternative to Solidity)

**Abstract decentralized concepts**
Oracles
Data management / file sharing (e.g. upspin.io)
Decentralized exchanges
Plasma chains
Payment channel
Assets (e.g. ERC-721)
Tooling for making dApps (e.g. Fabric(2))

**Subject matter**
Energy-related / smart grid (2)
IoT / machine-to-machine transactions / smart city
Social networks
Safe harbor / self-sovereign identity

**General**
Open & permissionless protocols
Blockchain

**Comment by pcowgill** [comment]
Yep, thanks @redsquirrel. I just updated the above comment to style that one with a strikethrough

**Comment by pcowgill** [comment]
@RickCarlino said, "...in the future, I would be interested in talking about Secure Scuttlebutt."

A future discussion of Secure Scuttlebutt seems like a great fit.

@RickCarlino also said, "Are topics usually centered around blockchain technology?"

Topics are _often_ centered around blockchain technology just because that's of interest to a lot of folks these days, but I certainly would like to make sure we include anything related to decentralized software if there's enough interest.

I'll note that things like IPFS and state channels are topics that often show up in the same conversation as blockchain or Ethereum, but those two technologies could be used completely independently. So anything that relates to creating a permissionless, cryptographically secure, decentralized architecture for the internet is of interest to me and hopefully the rest of the group too.

**Comment by wakingrufus** [comment]
I am currently working on a secure scuttlebutt implementation on the JVM. It is nowhere near complete though. I would love to hear someone who knows more about it talk about it. Eventually, when I finish my project, I will know a lot about it :)

**Comment by pcowgill** [comment]
@RickCarlino For Secure Scuttlebutt, do you think early Oct or early Dec would work better for you (with downtown Chicago as the location)? I have early Nov tentatively claimed for another topic/project.

**Comment by RickCarlino** [comment]
@pcowgill Let's go with early December, as that will give me ample prep time. Please drop me a line if you need anything between now and then.
